# Generated by Django 4.2 on 2023-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='visitas',
            field=models.ManyToManyField(related_name='consulta', to='clientes.visita'),
        ),
    ]
