# Generated by Django 4.2 on 2023-04-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_animal_visitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='visitas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mascota',
        ),
        migrations.AlterField(
            model_name='animal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='clientes.animal'),
        ),
    ]
